version: '3'

services:
  app:
    build: .
    container_name: process-file-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
    entrypoint: sh -c "npm install && npm run start:dev"

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./.docker/metabase-data:/metabase-data
      - ./environment/servers.json:/pgadmin4/servers.json
      - ./environment/pgpass:/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - postgres
    links:
      - postgres

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
