version: '3'

services:
  app:
    build:
      context: app
      network: host
    container_name: hubla-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - mysql
      - rabbitmq3

  process-file:
    build:
      context: process-file
      network: host
    container_name: hubla-process-file
    ports:
      - "50051:50051"
    volumes:
      - .:/home/node/app
    depends_on:
      - mysql
      - rabbitmq3

  mysql:
    image: mysql:8.0.33-debian
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hubla

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.12.0-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=hubla
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'